name: SysCall Backup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  SysCall-Backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar as dependencias da VM
        run: sudo apt-get update && sudo apt-get install -y postgresql-client zip

      - name: backup with pg_dump
        env:
          PWD: ${{ secrets.PWD }}
        run: |
          TIMESTAMP=$(TZ="America/Sao_Paulo" date +%Y%m%d_%H%M%S)
          BACKUP_NAME="backup_$TIMESTAMP.sql"
          ZIP_NAME="backup_$TIMESTAMP.zip"

          pg_dump -h ${{ secrets.HOST }} \
                  -p ${{ secrets.PORT }} \
                  -U ${{ secrets.USER }} \
                  -d ${{ secrets.DATABASE }} \
                  --no-password \
                  -f $BACKUP_NAME

          zip $ZIP_NAME $BACKUP_NAME

          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload on google drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: ${{ env.ZIP_NAME }}
          folderId: ${{ secrets.FOLDER_ID }}
